# Note the special trigger 'on: workflow_call:'

on:
  workflow_call:

jobs:
  setup:
    runs-on: ubuntu-latest
    name: Build Ubuntu - ${{ input.php }}

    steps:
      - name: Start MySQL service
        run: |
          sudo systemctl start mysql.service
          sudo mysql --host 127.0.0.1 --port 3306 -uroot -proot -e "SHOW DATABASES"
      - name: Create database
        run: sudo mysql --host 127.0.0.1 --port 3306 -uroot -proot -e "CREATE DATABASE webapps"
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.github', '.env');"
      - name: Install Dependencies
        run: |
          sudo composer self-update
          composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
      - name: Generate a new key
        run: php artisan key:generate --env=github
      - name: Set File & Directory Permissions
        run: |
          chmod -R 775 storage bootstrap/cache
          chmod 666 .env
      - name: Compile assets
        run: |
          npm install
          npm run production