name: WebApps Tests

on:
  push:
    branches:
      - develop
      - 'release/**'
  pull_request:
    branches: [develop]

jobs:

  cs-tests:
    runs-on: ubuntu-latest
    name: Test Coding Standards

    steps:
      - uses: ./github/workflows/build_environment.yml
      - name: Test Coding Standards
        run: vendor/bin/phpcs


  php-tests:
    runs-on: ubuntu-latest
    name: PHP ${{ matrix.php }} - Unit Test

    steps:
      - uses: ./github/workflows/build_environment.yml
      - name: Clear Laravel Cache
        run: php artisan cache:clear
      - name: Run Unit Tests
        run: php artisan test --coverage-clover=coverage.xml --env=github
      - name: Upload Unit coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.xml
          flags: unittests,${{ matrix.php }}
          name: codecov-umrella
          fail_ci_if_error: true
      
  js-tests:
    runs-on: ubuntu-latest
    name: UI/UX Tests

    steps:
      - uses: ./github/workflows/build_environment.yml
      - name: Run UI Tests
        run: npm run test-coverage
      - name: Upload UI coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage/coverage-final.json
          flags: uitests
          name: codecov-umrella
          fail_ci_if_error: true
      
